---
- name: Install and start Nginix
  hosts: all
  become: yes

  tasks:
     - name: Install nginix
       apt: 
         name: nginx
         state: present

     - name: Start Nginx
       service:
         name: nginx
         state: started
